interface SubjectGraphable {
    id?: string,
    glucose05th: number[],
    glucose10th: number[],
    glucose25th: number[],
    glucose50th: number[],
    glucose75th: number[],
    glucose90th: number[],
    glucose95th: number[],
    glucoseRecUpper?: number[], 
    glucoseRecLower?: number[], 
    iobRecUpper?: number[], 
    iobRecLower?: number[],
    basal05th: number[],
    basal10th: number[],
    basal25th: number[],
    basal50th: number[],
    basal75th: number[],
    basal90th: number[],
    basal95th: number[],
    iob05th: number[],
    iob10th: number[],
    iob25th: number[],
    iob50th: number[],
    iob75th: number[],
    iob90th: number[],
    iob95th: number[],
    tControlMean: number[],
    tdbasalMean: number,
    tdbolusMean: number,
    nmealsMean: number,
    mealHist: number[],
    mbolusHist: number[],
    cbolusHist: number[]
}

export default SubjectGraphable